repos:
  - repo: local
    hooks:
      - id: cfn-lint
        name: cfn-lint
        entry: cfn-lint
        language: system
        files: ^cfn/.*\.(ya?ml)$

      - id: cfn-guard-validate
        name: cfn-guard validate
        entry: cfn-guard
        args: ["validate", "-r", "rules/cfn-guard", "-d"]
        language: system
        files: ^cfn/.*\.(ya?ml)$
        require_serial: true

      - id: cfn-nag
        name: cfn-nag
        entry: cfn_nag_scan
        args: ["--input-path"]
        language: system
        files: ^cfn/.*\.(ya?ml)$
        require_serial: true
