AWSTemplateFormatVersion: '2010-09-09'
Description: Fixed demo – restricted SG + encrypted S3

Resources:
  DemoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true


  DemoSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Restrict SSH
      VpcId: vpc-1234567890abcdef0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.0.0.0/16   # example corp CIDR
          Description: "SSH from corp CIDR"
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 10.0.0.0/16
          Description: "HTTPS to corp services only"

